version: "3"
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    entrypoint: bash -c "while ! timeout 1 wget -qO- http://app:3001/container/status > /dev/null ; do sleep 1; done ; ./opt/bin/entry_point.sh"
    depends_on:
      - mongo
    volumes:
      - /dev/shm:/dev/shm
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      MONGO_URL:  'mongodb://mongo/scraaam'
      DOCKER:       'true'
      APP_PORT:      3001
      APP_TIMEOUT:  10000
      APP_RETRY:      500
    depends_on:
      - mongo
  e2e:
    build:
      context: .
      dockerfile:  Dockerfile-e2e
    environment:
      APP_PORT:    3001
      APP_URL:     "http://app:3001"
    depends_on:
      - app
    entrypoint: bash -c "while ! timeout 1 wget -qO- http://selenium:4444/wd/hub > /dev/null ; do sleep 1; done; npm run end-to-end-test -- protractor.conf.js --seleniumAddress http://selenium:4444/wd/hub"
